version: "2"
services:
  app:
   # build: ./app
    image: mybackimage
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      MYSQL_DATABASE: "destiny_cards"
      MYSQL_PWD: 'root'
      MYSQL_USER: "root"
      MYSQL_URL: "db"
      MYSQL_PORT: "3306"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  web:
    image: myfrontimage      
    ports:
      - "1234:80"
